version: '3.1'

services:
  php:
    build:
      context: ./etc/docker/php
    depends_on:
      - database
    volumes:
      - ./:/app
      - ~/.composer:/root/.composer
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=sleep-tracker.local"
      XDEBUG_SESSION: 1

  encore:
    image: node:14-alpine
    volumes:
      - .:/app
    working_dir: /app
#    command: [ "yarn", "add", "bootstrap-datepicker", "--dev" ]
    command: [ "yarn", "dev" ]

  nginx:
    image: demroos/symfony-nginx:latest
    working_dir: /app
    links:
      - php:php-fpm
    depends_on:
      - php
    ports:
      - '${NGINX_PORT:-8080}:80'
    volumes:
      - ./:/app
  database:
    image: postgres:13
    ports:
      - '${DB_PORT:-5452}:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: sleep-tracker
      POSTGRES_DB: sleep-tracker
      POSTGRES_PASSWORD: 123456

volumes:
  dbdata:
    driver: local
